spring.application.name=banking-app

## MySQL Connection Settings (Port-ai 3306-nu mathiyachu)
#spring.datasource.url=jdbc:mysql://localhost:3306/banking_db
#spring.datasource.username=root
#spring.datasource.password=MohanThiru@123
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
## JPA / Hibernate Settings
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
# Aiven MySQL Connection Settings
spring.datasource.url=jdbc:mysql://mysql-2e0e65d8-banking-db-online.l.aivencloud.com:14166/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_CfAfUaMyANdj2KeJvDL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Pudhu version dialect name
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

springdoc.packages-to-scan=com.bankApp.banking_app.controller
springdoc.swagger-ui.path=/swagger-ui.html

# Email Settings
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mukesh638064@gmail.com
spring.mail.password=yymldtfzwdmrcsfx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Server Port
server.port=8080